version: '3.9'

services:
  ci:
    container_name: gan_shmuel_ci
    build: .
    networks:
      - BlueTeam
      - test_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/sh -c "./scripts/deploy.sh && gunicorn app:app --bind 0.0.0.0:8080"
    expose:
      - "8080"

  nginx:
    image: nginx:stable-alpine
    command: /bin/sh -c "sleep 60 && exec nginx -g 'daemon off;'"
    ports:
      - "8080:8080"
      - "8082:8082"
      - "8083:8083"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ci
    networks:
      - BlueTeam

networks:
  BlueTeam:
    name: BlueTeam
  test_network:
    name: test_network
