version: '3.9'

services:
  ci:
    container_name: gan_shmuel_ci
    build: .
    networks:
      - BlueTeam
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "8080"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:8080"
      - "8082:8082"
      - "8083:8083"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ci
    networks:
      - BlueTeam

networks:
  BlueTeam:
    name: BlueTeam
