version: '3'

services:
  ci:
    container_name: test-branch-db
    image: hello-world:latest
    expose:
      - "8080"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge