services:
 pythonapp:
  build: ./python/
  command: sh -c "sleep 15s ; python3 ./app.py"
  volumes:
   - ./mysql/in/:/in/ 
  env_file:
   - ./sql.env
  depends_on:
   - billing-mysql
  ports:
   - "8082:80"
 billing-mysql:
  build: ./mysql/
  restart: always
  volumes:
   - ./mysql/billingdb.sql:/docker-entrypoint-initdb.d/billingdb.sql
  environment:
   MYSQL_DATABASE: "billingdb"
   MYSQL_ROOT_PASSWORD: "root"
  env_file:
   - ./sql.env
  ports:
   - "8081:3306"
