networks:
 BlueTeam:
  name: BlueTeam
services:
 
 pythonapp:
  container_name: billing-app
  build: ./python/
  networks:
   - BlueTeam
  command: sh -c "sleep 15s ; python3 ./app.py"
  volumes:
<<<<<<< HEAD:billing/docker-compose.yaml
   - '/etc/localtime:/etc/localtime:ro'
=======
   - ./mysql/in/:/in/ 
>>>>>>> 3fd345b:billing/docker-compose.yml
  env_file:
   - ./sql.env
  depends_on:
   - billing-mysql
  
 billing-mysql:
  container_name: billing-database
  build: ./mysql/
  networks:
   - BlueTeam
  restart: always
  volumes:
   - ./mysql/billingdb.sql:/docker-entrypoint-initdb.d/billingdb.sql
  environment:
   MYSQL_DATABASE: "billdb"
   MYSQL_ROOT_PASSWORD: "root"
  env_file:
   - ./sql.env
