version: '3.9'
<<<<<<< HEAD
=======


>>>>>>> 69a30cb (dump to dumps)
services:
  db:
    networks:
      - BlueTeam
    container_name: weight-database
    image: mysql:5.7
    networks:
      - BlueTeam
    expose:
      - 3306
    env_file:
      - ./.env
    volumes:
      - ./datadump:/docker-entrypoint-initdb.d
      - ./datadir:/var/lib/mysql
    stdin_open: true
    tty: true

  app:
    networks:
      - BlueTeam
    container_name: weight-app
    env_file:
      - ./.env
    build: .
    networks:
      - BlueTeam
    ports:
      - "5050:5000"
    command: flask run
    links:
      - "db"
<<<<<<< HEAD

networks:
  BlueTeam:
    name: BlueTeam
=======
networks:
  BlueTeam:
    name: BlueTeam

    
>>>>>>> 69a30cb (dump to dumps)
