version: '3.9'

services:
  db:
    container_name: weight-database
    image: mysql:5.7
    networks:
      - BlueTeam
    expose:
      - 3306
    restart: always
    volumes:
      - ./datadump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: "weight"
      MYSQL_ROOT_PASSWORD: "root"
    env_file:
      - ./.env

  app:
    container_name: weight-app
    environment:
      MYSQL_DATABASE: "weight"
      MYSQL_ROOT_PASSWORD: "root"
    env_file:
      - ./.env
    build: .
    networks:
      - BlueTeam
    ports:
      - "5000:8000" # for local testing
    command: python ./weight.py
    depends_on:
      - db

networks:
  BlueTeam:
    name: BlueTeam
