version: '3.9'

services:
  db:
    container_name: weight-database
    image: mysql:5.7
    networks:
      - BlueTeam
    expose:
      - 3306
    env_file:
      - ./.env
    volumes:
      - ./datadump:/docker-entrypoint-initdb.d
      - ./datadir:/var/lib/mysql

  app:
    container_name: weight-app
    env_file:
      - ./.env
    build: .
    networks:
      - BlueTeam
    ports:
      - "5000:8000" # for local testing
    command: python ./weight.py
    depends_on:
      - db
    links:
      - "db"

networks:
  BlueTeam:
    name: BlueTeam
