version: '3.9'
services:
  db:
    container_name: weight-database
    image: mysql:5.7
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./datadump:/docker-entrypoint-initdb.d
    stdin_open: true
    tty: true
  app:
    container_name: weight-app
    build: .
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
    ports:
      - "80:5000"
    command: flask run
    links: 
      - "db"
